[manager]
prepend_keymap = [
    # Override default yank-cut-paste behavior to use 2-action keys like ranger
    { on = [ "y", "y" ], run = "yank", desc = "Yank selected files" },
    { on = [ "d", "d" ], run = "yank --cut", desc = "Cut selected files" },
    { on = [ "p", "p" ], run = "paste", desc = "Paste" },
    { on = [ "p", "P" ], run = "paste --force", desc = "Paste (Overwrite)" },
    { on = [ "d", "D" ], run = "remove --permanently", desc = "Delete" }
]
