format = '''
[](fg:bright-blue)$os$hostname[](fg:bright-blue bg:bright-black)[ ](bg:bright-black fg:black)$username[](fg:bright-black) $directory $git_branch$git_status$git_state
$character
'''

[os]
disabled = false
style = 'bold bg:bright-blue'

[os.symbols]
Windows = ""
Ubuntu = ""

[hostname]
ssh_only = false
format = '[ $ssh_symbol$hostname]($style)'
style = 'bold bg:bright-blue'

[username]
show_always = true
format = '[$user]($style)'
style_user = 'bold fg:bright-white bg:bright-black'
style_root = 'bold fg:red bg:bright-black'

[directory]
format = '[](bright-white)[📁 $path]($style)[$read_only]($read_only_style)[](bright-white)'
style = 'bold bg:bright-white fg:black'
truncation_length = 5
truncation_symbol = '.../'

[git_branch]
format = '[](bright-black)[$symbol$branch(:$remote_branch)]($style)'
symbol = ' '
style = 'bold bg:bright-black'

[git_status]
style = 'bold bg:bright-black'
format = '([ $all_status$ahead_behind]($style))[](bright-black)'

[character]
success_symbol = '[❯](bold fg:bright-white)'